package com.seyone22.shot.data.domain.repository

import com.seyone22.shot.data.local.dao.RoundDao
import com.seyone22.shot.data.local.entity.DistanceEntity
import com.seyone22.shot.data.local.entity.RoundEntity
import com.seyone22.shot.data.local.entity.RoundWithDistances
import kotlinx.coroutines.flow.Flow

class LocalRoundRepository(
    private val roundDao: RoundDao
) : RoundRepository {

    override fun getAllRoundsStream(): Flow<List<RoundWithDistances>> = roundDao.getAllRoundsWithDistances()

    override fun getRoundStream(id: Long): Flow<RoundWithDistances?> = roundDao.getRoundWithDistancesById(id)

    override suspend fun insertRoundWithDistances(round: RoundEntity, distances: List<DistanceEntity>) {
        // We insert the round first to get its autogenerated ID,
        // then assign that ID to all distances before inserting them.
        val roundId = roundDao.insertRound(round)
        val distancesWithRoundId = distances.map { it.copy(roundId = roundId) }
        roundDao.insertDistances(distancesWithRoundId)
    }

    // <-- ADD THIS -->
    override fun getRoundWithDistancesStream(id: Long): Flow<RoundWithDistances?> = roundDao.getRoundWithDistances(id)
}